name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.2.0
      with:
        go-version: '1.18'

    - name: Install golangci-lint
      shell: bash
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.48.0

    - name: Build
      run: make build

    - name: Lint
      run: make lint

    - name: Unit tests
      run: make test

    - name: Integration tests
      run: make integration

